src/Entity/Cursus.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\CursusRepository")
 */
class Cursus
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Instructeur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $opmerking;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_aantal;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FactuurRegel", mappedBy="Cursus_Id")
     */
    private $factuurRegels;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CursusType", inversedBy="cursuses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $CursusType;

    public function __construct()
    {
        $this->factuurRegels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getCursusType()
    {
        return $this->CursusType;
    }

    /**
     * @param mixed $CursusType
     */
    public function setCursusType($CursusType): void
    {
        $this->CursusType = $CursusType;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): self
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getInstructeur(): ?string
    {
        return $this->Instructeur;
    }

    public function setInstructeur(string $Instructeur): self
    {
        $this->Instructeur = $Instructeur;

        return $this;
    }

    public function getOpmerking(): ?string
    {
        return $this->opmerking;
    }

    public function setOpmerking(?string $opmerking): self
    {
        $this->opmerking = $opmerking;

        return $this;
    }

    public function getMaxAantal(): ?int
    {
        return $this->max_aantal;
    }

    public function setMaxAantal(int $max_aantal): self
    {
        $this->max_aantal = $max_aantal;

        return $this;
    }

    /**
     * @return Collection|FactuurRegel[]
     */
    public function getFactuurRegels(): Collection
    {
        return $this->factuurRegels;
    }

    public function addFactuurRegel(FactuurRegel $factuurRegel): self
    {
        if (!$this->factuurRegels->contains($factuurRegel)) {
            $this->factuurRegels[] = $factuurRegel;
            $factuurRegel->setCursusId($this);
        }

        return $this;
    }

    public function removeFactuurRegel(FactuurRegel $factuurRegel): self
    {
        if ($this->factuurRegels->contains($factuurRegel)) {
            $this->factuurRegels->removeElement($factuurRegel);
            // set the owning side to null (unless already changed)
            if ($factuurRegel->getCursusId() === $this) {
                $factuurRegel->setCursusId(null);
            }
        }

        return $this;
    }
}

src/Entity/CursusType.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\CursusTypeRepository")
 */
class CursusType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $naam;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_aantal;

    /**
     * @ORM\Column(type="integer")
     */
    private $prijs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Cursus", mappedBy="CursusType")
     */
    private $cursuses;

    public function __construct()
    {
        $this->cursuses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNaam(): ?string
    {
        return $this->naam;
    }

    public function setNaam(string $naam): self
    {
        $this->naam = $naam;

        return $this;
    }

    public function getMaxAantal(): ?int
    {
        return $this->max_aantal;
    }

    public function setMaxAantal(int $max_aantal): self
    {
        $this->max_aantal = $max_aantal;

        return $this;
    }

    public function getPrijs(): ?int
    {
        return $this->prijs;
    }

    public function setPrijs(int $prijs): self
    {
        $this->prijs = $prijs;

        return $this;
    }

    /**
     * @return Collection|Cursus[]
     */
    public function getCursuses(): Collection
    {
        return $this->cursuses;
    }

    public function addCursus(Cursus $cursus): self
    {
        if (!$this->cursuses->contains($cursus)) {
            $this->cursuses[] = $cursus;
            $cursus->setCursusType($this);
        }

        return $this;
    }

    public function removeCursus(Cursus $cursus): self
    {
        if ($this->cursuses->contains($cursus)) {
            $this->cursuses->removeElement($cursus);
            // set the owning side to null (unless already changed)
            if ($cursus->getCursusType() === $this) {
                $cursus->setCursusType(null);
            }
        }

        return $this;
    }
}

src/Form/CursusType.php
<?php

namespace App\Form;

use App\Entity\Cursus;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CursusType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
//            ->add('cursus_type')
            ->add('date_time')
            ->add('Instructeur')
            ->add('opmerking')
            ->add('max_aantal')
            ->add('CursusType', EntityType::class, [
                'class' => \App\Entity\CursusType::class,
                'choice_label'  => 'naam',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Cursus::class,
        ]);
    }
}

src/Controller/CursusController.php
<?php

namespace App\Controller;

use App\Entity\Cursus;
use App\Form\CursusType;
use App\Repository\CursusRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/cursus")
 */
class CursusController extends AbstractController
{
    /**
     * @Route("/", name="cursus_index", methods="GET")
     */
    public function index(CursusRepository $cursusRepository): Response
    {
        return $this->render('cursus/index.html.twig', ['cursuses' => $cursusRepository->findAll()]);
    }

    /**
     * @Route("/new", name="cursus_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $cursus = new Cursus();
        $form = $this->createForm(CursusType::class, $cursus);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($cursus);
            $em->flush();

            return $this->redirectToRoute('cursus_index');
        }

        return $this->render('cursus/new.html.twig', [
            'cursus' => $cursus,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="cursus_show", methods="GET")
     */
    public function show(Cursus $cursus): Response
    {
        return $this->render('cursus/show.html.twig', ['cursus' => $cursus]);
    }

    /**
     * @Route("/{id}/edit", name="cursus_edit", methods="GET|POST")
     */
    public function edit(Request $request, Cursus $cursus): Response
    {
        $form = $this->createForm(CursusType::class, $cursus);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('cursus_index', ['id' => $cursus->getId()]);
        }

        return $this->render('cursus/login.html.twig', [
            'cursus' => $cursus,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="cursus_delete", methods="DELETE")
     */
    public function delete(Request $request, Cursus $cursus): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cursus->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($cursus);
            $em->flush();
        }

        return $this->redirectToRoute('cursus_index');
    }
}

templates/cursus/_delete_form.html.twig
<form method="post" action="{{ path('cursus_delete', {'id': cursus.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cursus.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cursus/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/cursus/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cursus{% endblock %}

{% block body %}
    <h1>Edit Cursus</h1>

    {{ include('cursus/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('cursus_index') }}">back to list</a>

    {{ include('cursus/_delete_form.html.twig') }}
{% endblock %}

templates/cursus/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cursus index{% endblock %}

{% block body %}
    <h1>Cursus index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cursus_type</th>
                <th>Date_time</th>
                <th>Instructeur</th>
                <th>Opmerking</th>
                <th>Max_aantal</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cursus in cursuses %}
            <tr>
                <td>{{ cursus.id }}</td>
                <td>{{ cursus.cursusType.naam }}</td>
                <td>{{ cursus.dateTime ? cursus.dateTime|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ cursus.Instructeur }}</td>
                <td>{{ cursus.opmerking }}</td>
                <td>{{ cursus.maxAantal }}</td>
                <td>
                    <a href="{{ path('cursus_show', {'id': cursus.id}) }}">show</a>
                    <a href="{{ path('cursus_edit', {'id': cursus.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('cursus_new') }}">Create new</a>
{% endblock %}

templates/cursus/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cursus{% endblock %}

{% block body %}
    <h1>Create new Cursus</h1>

    {{ include('cursus/_form.html.twig') }}

    <a href="{{ path('cursus_index') }}">back to list</a>
{% endblock %}

templates/cursus/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cursus{% endblock %}

{% block body %}
    <h1>Cursus</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cursus.id }}</td>
            </tr>
            <tr>
                <th>Cursus_type</th>
                <td>{{ cursus.cursusType }}</td>
            </tr>
            <tr>
                <th>Date_time</th>
                <td>{{ cursus.dateTime ? cursus.dateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Instructeur</th>
                <td>{{ cursus.Instructeur }}</td>
            </tr>
            <tr>
                <th>Opmerking</th>
                <td>{{ cursus.opmerking }}</td>
            </tr>
            <tr>
                <th>Max_aantal</th>
                <td>{{ cursus.maxAantal }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('cursus_index') }}">back to list</a>

    <a href="{{ path('cursus_edit', {'id': cursus.id}) }}">edit</a>

    {{ include('cursus/_delete_form.html.twig') }}
{% endblock %}